### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by soywiz** [bridgedotnet/homebrew-cli#1]
Looks like this is wrong?
https://github.com/bridgedotnet/homebrew-cli/blob/f793415789983912e4ef33e6796cf4b5b2baa9dd/Formula/bridge.rb#L15

```
brew install bridgedotnet/cli/bridge

==> Tapping bridgedotnet/cli
Cloning into '/usr/local/Homebrew/Library/Taps/bridgedotnet/homebrew-cli'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/bridgedotnet/homebrew-cli/Formula/bridge.rb
bridge: /usr/local/Homebrew/Library/Taps/bridgedotnet/homebrew-cli/Formula/bridge.rb:16: syntax error, unexpected tIDENTIFIER, expecting end
    sha256 "378d65394b9040ad61f0b645002...
    ^~~~~~
/usr/local/Homebrew/Library/Taps/bridgedotnet/homebrew-cli/Formula/bridge.rb:133: syntax error, unexpected end, expecting end-of-input
Error: Cannot tap bridgedotnet/cli: invalid syntax in tap!
```

**Comment by geoffreymcgill** [comment]
Thanks for letting us know about this defect and submitting the PR. We will investigate right away.

**Comment by fabriciomurta** [comment]
Silly slash. I'll double check if every hash is right and fix them.

**Comment by fabriciomurta** [comment]
Sierra, High Sierra and Catalina bottles working just fine. Thanks again for reporting the issue!

**Comment by soywiz** [comment]
Nice :) I just noticed this last week when I tried Bridge for the first time. This week I had the same issue, so I checked. Probably pressed a key before doing the commit; I have had problems like that before, not a big deal. 
I forked it, and tried to install it before submitting the PR and seemed to work.

Thanks to you for the project!
Best regards
